# Generated by Django 3.1.1 on 2020-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
